services:
  lifedb:
    container_name: lifedatabase
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: kishiin
      POSTGRES_DB: lifedatabase
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: "600s"
      timeout: "5s"
      retries: 5
    secrets:
      - db_password
    volumes:
      - ..\Database:/var/lib/postgresql/data/pgdata
      - .\postgresql.conf:/etc/postgresql/postgresql.conf
      - .\Logs:/etc/postgresql/logs
      - .\Scripts:/docker-entrypoint-initdb.d
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

secrets:
  db_password:
    file: postgres_password.txt